(function(root){
 'use strict';const B=root.TaskerBoq,M=root.TaskerModuleStatusModel;
 const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const num=n=>n===null?'—':new Intl.NumberFormat('sr-Latn-RS',{maximumFractionDigits:3}).format(n),money=n=>n===null?'Cena nije uneta':num(n)+' €';
 let ctx,tab='overview',last='',currentReport=null;
 const button=(text,attr)=>'<button type="button" class="ms-button" '+attr+'>'+text+'</button>';
 const badge=p=>'<span class="bq-badge" style="--bq-color:'+M.statuses[p?.status||'new'].color+'">'+esc(M.statuses[p?.status||'new'].label)+'</span>';
 function modal(html){let d=document.getElementById('bq-dialog');if(!d){d=document.createElement('dialog');d.id='bq-dialog';d.className='ms-dialog bq-dialog';document.getElementById('module-status').append(d)}d.innerHTML='<div class="bq-close">'+button('✕ Zatvori','data-bq-close')+'</div>'+html+'<p id="bq-error" role="alert"></p>';if(!d.open)d.showModal();return d}
 function table(rows,proof=false){return '<div class="bq-scroll"><table><thead><tr><th>BOQ / faza</th><th>Status</th><th>%</th><th>Ugovoreno</th><th>Izvedeno</th><th>Preostalo</th></tr></thead><tbody>'+rows.map(r=>'<tr><td>'+button(esc(r.boq)+' · '+esc(r.name),'data-bq-item="'+esc(r.id)+'"')+'<small>'+esc(r.section)+'</small></td><td>'+badge(r.phase)+(r.phase?.reviewDate?'<small>Proveri staru izvedenost</small>':'')+'</td><td>'+num(r.percent)+'</td><td>'+num(r.quantity)+' '+esc(r.unit)+'</td><td>'+num(r.done)+'</td><td>'+num(r.remaining)+'</td></tr>').join('')+'</tbody></table></div>'}
 function renderPanel(){const {state,m}=ctx,host=document.getElementById('bq-panel');if(!host)return;const rows=B.rows(state,m);
  if(tab==='boq')host.innerHTML='<h3>'+esc(m.type)+' troškovnik · '+esc(m.name)+'</h3><p>Količine se računaju iz faza. Nema ponovnog unosa.</p>'+table(rows);
  if(tab==='proof')host.innerHTML='<h3>Dokaznica · '+esc(m.name)+'</h3><p>Izaberi stavku za fotografiju, skicu ili napomenu. Mesečna dokaznica za sve module dostupna je u obračunu.</p>'+rows.map(r=>'<article class="bq-phase">'+button(esc(r.boq)+' · '+esc(r.name),'data-bq-item="'+esc(r.id)+'"')+'<p>'+num(r.done)+' / '+num(r.quantity)+' '+esc(r.unit)+'</p><small>'+esc(r.phase?.note||'Bez napomene')+'</small></article>').join('');
  if(tab==='photos'){const photos=rows.flatMap(r=>(r.phase?.evidence||[]).map(e=>({...e,title:r.boq+' · '+r.name})));host.innerHTML='<h3>Fotografije i skice</h3><p>Dokaz se dodaje iz detalja BOQ stavke.</p><div class="bq-photos">'+(m.photo?'<figure><img src="'+m.photo+'" alt="Fotografija modula"></figure>':'')+photos.map(e=>'<figure><img src="'+e.image+'" alt="'+esc(e.caption||e.title)+'"><figcaption>'+esc(e.title)+'<br>'+esc(e.caption)+'</figcaption></figure>').join('')+'</div>'}
  if(tab==='history')host.innerHTML='<h3>Istorija · '+esc(m.name)+'</h3><ol class="bq-history">'+[...m.history].reverse().map(e=>'<li><time>'+esc(new Date(e.at).toLocaleString('sr-Latn-RS'))+'</time><p>'+esc(e.text)+'</p>'+(e.occurredOn?'<small>Datum rada: '+esc(e.occurredOn)+'</small>':'')+'</li>').join('')+'</ol>';
  if(tab==='phases')host.innerHTML='<h3>Faze · '+esc(m.type)+'</h3><p>Završeno = 100%. Za delimične radove otvori „Detalji / procenat“.</p>'+rows.map(r=>'<article class="bq-phase"><small>'+esc(r.section)+' · BOQ '+esc(r.boq)+'</small><b>'+esc(r.phase.name)+'</b><div>'+badge(r.phase)+' <strong>'+num(r.percent)+'%</strong></div><select aria-label="Status '+esc(r.name)+'" data-bq-status="'+esc(r.phase.id)+'">'+Object.entries(M.statuses).filter(([k])=>k!=='ready').map(([k,v])=>'<option value="'+k+'" '+(r.phase.status===k?'selected':'')+'>'+esc(v.label)+'</option>').join('')+button('Detalji / procenat','data-bq-item="'+esc(r.id)+'"')+(r.phase.mapping==='new'?'<small>Nova BOQ faza. Proveri vezu sa ranijim radovima.</small>':'')+'</article>').join('')+'<details><summary>Dodatne / ranije faze bez BOQ veze (sačuvane)</summary>'+m.phases.filter(p=>!p.boqItemId).map(p=>'<p>'+esc(p.name)+' · '+badge(p)+'<select aria-label="Status ranije faze '+esc(p.name)+'" data-ms-phase="'+esc(p.id)+'">'+Object.entries(M.statuses).filter(([k])=>k!=='ready').map(([k,v])=>'<option value="'+k+'" '+(p.status===k?'selected':'')+'>'+esc(v.label)+'</option>').join('')+'</select></p>').join('')+'</details>';
 }
 function mount(c){ctx=c;const {box,m}=c;if(last!==m.id){tab='overview';last=m.id}const header=box.querySelector('.ms-detail-title'),overview=document.createElement('div');overview.id='bq-overview';while(header.nextSibling)overview.append(header.nextSibling);box.append(overview);const nav=document.createElement('nav');nav.className='bq-tabs';nav.setAttribute('aria-label','Detalji modula');nav.innerHTML=[['overview','Pregled'],['phases','Faze'],['boq','Troškovnik'],['proof','Dokaznica'],['photos','Fotografije'],['history','Istorija']].map(([key,name])=>button(name,'data-bq-tab="'+key+'" aria-pressed="'+(tab===key)+'"')).join('');header.after(nav);const panel=document.createElement('div');panel.id='bq-panel';box.append(panel);overview.hidden=tab!=='overview';panel.hidden=tab==='overview';
  // Phase editing has a single visible home; old controls remain in the overview DOM for compatibility.
  overview.querySelectorAll('.ms-phases,#ms-phase-form').forEach(e=>e.hidden=true);for(const h of overview.querySelectorAll('h3'))if(h.textContent==='Faze izrade')h.hidden=true;
  const hint=overview.querySelector('.ms-hint');if(hint)hint.textContent='Prosek izvedenosti primenjivih BOQ faza; nije finansijski procenat.';
  renderPanel();
 }
 function detail(id){const {state,m}=ctx,r=B.rows(state,m).find(r=>r.id===id);if(!r)return;const p=r.phase;
  modal('<h2>'+esc(m.name)+' · BOQ '+esc(r.boq)+'</h2><h3>'+esc(r.name)+'</h3><p>'+esc(r.description)+'</p><p>'+esc(r.notes)+'</p><div class="bq-totals"><span>Ugovoreno <b>'+num(r.quantity)+' '+esc(r.unit)+'</b></span><span>Izvedeno <b>'+num(r.done)+'</b></span><span>Preostalo <b>'+num(r.remaining)+'</b></span></div><form id="bq-progress-form" data-phase="'+esc(p.id)+'"><p>Ovo je isti zapis faze u Statusu modula.</p><label>Status<select name="status">'+Object.entries(M.statuses).filter(([k])=>k!=='ready').map(([k,v])=>'<option value="'+k+'" '+(p.status===k?'selected':'')+'>'+esc(v.label)+'</option>').join('')+'</select></label><label>Izvedeno %<input name="percent" type="number" min="0" max="100" step="0.01" value="'+(p.percent??0)+'" required></label><label>Datum izvedenosti / završetka<input name="effectiveOn" type="date" max="'+M.today()+'" value="'+M.today()+'" required></label><label>Datum početka<input name="startedOn" type="date" value="'+esc(p.startedOn||'')+'"></label><label>Napomena<textarea name="note">'+esc(p.note||'')+'</textarea></label><label>Razlog blokade / čekanja<textarea name="reason">'+esc(p.reason||'')+'</textarea></label><button class="ms-button primary" type="submit">Sačuvaj fazu</button></form><details><summary>Povezivanje sa ranijom fazom</summary><p>Ne povezujte različite vrste prodora bez provere opisa. Nova faza ostaje zasebna ako nema odgovarajućeg ranijeg rada.</p><form id="bq-map-form" data-item="'+esc(id)+'"><select name="phase">'+m.phases.filter(x=>!x.boqItemId||x.id===p.id).map(x=>'<option value="'+esc(x.id)+'" '+(x.id===p.id?'selected':'')+'>'+esc(x.name)+'</option>').join('')+'</select><button type="submit" class="ms-button">Potvrdi povezivanje</button></form></details><h3>Dokazi</h3><label>Dodaj fotografiju ili skicu<input type="file" accept="image/png,image/jpeg,image/webp" data-bq-upload="'+esc(p.id)+'"></label><div class="bq-photos">'+(p.evidence||[]).map(e=>'<figure><img src="'+e.image+'" alt="Dokaz"><figcaption>'+esc(e.caption)+'</figcaption></figure>').join('')+'</div>');
 }
 function reportHTML(report){return '<h2>Mesečni obračun · '+esc(report.month)+'</h2><p>Verzija '+(report.version||'pregled')+' · Svaki troškovnik prikazan je odvojeno. Negativna mesečna količina označava korekciju.</p>'+report.groups.map(g=>'<section><h3>'+esc(g.type)+' · '+esc(g.revision)+'</h3><div class="bq-scroll"><table><thead><tr><th>BOQ / rad</th><th>Status</th><th>JM</th><th>Ugovoreno</th><th>Prethodno</th><th>Ovaj mesec</th><th>Ukupno</th><th>Preostalo</th><th>Vrednost meseca</th></tr></thead><tbody>'+g.rows.map(r=>'<tr><td>'+esc(r.boq)+' '+esc(r.name)+(r.proof.some(p=>p.review)?'<small>⚠ Proveriti povezivanje / staru izvedenost</small>':'')+'</td><td>'+badge({status:r.proof.length&&r.proof.every(p=>p.status==='na')?'na':r.proof.some(p=>['blocked','waiting'].includes(p.status))?'waiting':r.contracted>0&&r.total===r.contracted?'done':r.total>0?'active':'new'})+'</td><td>'+esc(r.unit)+'</td>'+['contracted','previous','current','total','remaining'].map(k=>'<td>'+num(r[k])+'</td>').join('')+'<td>'+money(r.values?.current??null)+'</td></tr>').join('')+'</tbody></table></div><h4>Dokaznica po modulima · '+esc(g.type)+'</h4>'+g.rows.filter(r=>r.proof.some(p=>p.total||p.current)).map(r=>'<details><summary>'+esc(r.boq)+' '+esc(r.name)+' — ovaj mesec '+num(r.current)+' '+esc(r.unit)+'</summary>'+r.proof.filter(p=>p.total||p.current).map(p=>'<p>'+esc(p.module)+': prethodno '+num(p.previous)+', ovaj mesec '+num(p.current)+', ukupno '+num(p.total)+' '+esc(r.unit)+(p.note?' · '+esc(p.note):'')+'</p>').join('')+'</details>').join('')+'<p>Vrednost: prethodno '+money(g.rows.every(r=>r.values)?g.rows.reduce((s,r)=>s+r.values.previous,0):null)+' · ovaj mesec '+money(g.rows.every(r=>r.values)?g.rows.reduce((s,r)=>s+r.values.current,0):null)+' · ukupno '+money(g.rows.every(r=>r.values)?g.rows.reduce((s,r)=>s+r.values.total,0):null)+' · preostalo '+money(g.rows.every(r=>r.values)?g.rows.reduce((s,r)=>s+r.values.remaining,0):null)+'</p></section>').join('')}
 function reportForm(){const state=root.TaskerModuleBridge.state();modal('<h2>Generiši mesečni obračun</h2><form id="bq-report-form"><label>Mesec<input type="month" name="month" value="'+M.today().slice(0,7)+'" required></label><label>Troškovnik<select name="scope"><option value="ALL">SVE — odvojeno</option>'+B.templates(state).map(t=>'<option>'+esc(t.type)+'</option>').join('')+'</select></label><button type="submit" class="ms-button primary">GENERIRAJ MJESEČNI OBRAČUN</button></form><h3>Sačuvane verzije</h3>'+[...state.boq.reports].reverse().map(r=>button(esc(r.month)+' · '+esc(r.scope)+' · v'+r.version,'data-bq-report="'+esc(r.id)+'"')).join(''))}
 function showReport(r){currentReport=r;modal(reportHTML(r)+'<div class="ms-actions">'+button('Preuzmi obračun (HTML)','data-bq-export')+button('Preuzmi podatke (JSON)','data-bq-json')+'</div><p>HTML dokument možeš otvoriti u pregledaču i odštampati ili sačuvati kao PDF. Ovo je nacrt za proveru i odobrenje, ne potvrda nadzora.</p>')}
 function admin(){const s=root.TaskerModuleBridge.state();modal('<h2>TROŠKOVNICI</h2><p>Originalne količine i opisi su zaključani. Jedinične cene su opcione, u EUR. Dodati novi tip: preuzmi JSON obrazac, popuni njegove stavke i uvezi.</p>'+button('Preuzmi rezervnu kopiju modula','data-bq-backup')+button('Preuzmi stanje pre BOQ nadogradnje','data-bq-backup-old')+button('Preuzmi obrazac novog tipa','data-bq-template-example')+'<label>+ DODAJ TROŠKOVNIK<input type="file" data-bq-template accept="application/json"></label>'+B.templates(s).map(t=>'<details><summary>'+esc(t.type)+' TROŠKOVNIK · '+t.items.length+' stavki</summary><p>'+esc(t.source)+' · '+esc(t.revision)+'</p><div class="bq-scroll"><table><thead><tr><th>BOQ / stavka</th><th>Količina</th><th>Mapirane faze / moduli</th><th>Cena €</th></tr></thead><tbody>'+t.items.map(i=>'<tr><td>'+esc(i.boq)+' '+esc(i.name)+'<small>'+esc(i.section)+'</small></td><td>'+num(i.quantity)+' '+esc(i.unit)+'</td><td>'+s.modules.filter(m=>m.boqTemplateId===t.id).map(m=>{const p=B.phase(m,i);return esc(m.name)+': '+esc(p?.name||'Nepovezano')+' ('+(p?.mapping==='new'?'provera':p?.mapping==='confirmed'?'potvrđeno':'direktno')+')'}).join('<br>')+'</td><td><input aria-label="Cena '+esc(i.name)+'" data-bq-price="'+esc(i.id)+'" data-template="'+esc(t.id)+'" type="number" min="0" step="0.01" value="'+(i.unitPrice??'')+'"></td></tr>').join('')+'</tbody></table></div></details>').join(''))}
 function saveFile(data,name,type){const url=URL.createObjectURL(new Blob([data],{type})),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),60000)}
 document.addEventListener('click',e=>{const b=e.target.closest('[data-bq-tab],[data-bq-item],[data-bq-close],[data-bq-admin],[data-bq-monthly],[data-bq-report],[data-bq-export],[data-bq-json],[data-bq-template-example]');if(!b)return;try{if(b.hasAttribute('data-bq-close')){b.closest('dialog').close();return}if(b.dataset.bqTab){tab=b.dataset.bqTab;document.getElementById('bq-overview').hidden=tab!=='overview';document.getElementById('bq-panel').hidden=tab==='overview';document.querySelectorAll('[data-bq-tab]').forEach(x=>x.setAttribute('aria-pressed',String(x.dataset.bqTab===tab)));renderPanel()}if(b.dataset.bqItem)detail(b.dataset.bqItem);if(b.hasAttribute('data-bq-admin'))admin();if(b.hasAttribute('data-bq-monthly'))reportForm();if(b.dataset.bqReport)showReport(root.TaskerModuleBridge.state().boq.reports.find(r=>r.id===b.dataset.bqReport));if(b.hasAttribute('data-bq-json'))saveFile(JSON.stringify(currentReport,null,2),'Obracun-'+currentReport.month+'.json','application/json');if(b.hasAttribute('data-bq-export'))saveFile('<!doctype html><meta charset="utf-8"><title>Mesečni obračun</title><style>body{font:14px Arial;margin:25px}table{border-collapse:collapse;width:100%}th,td{border:1px solid #aaa;padding:6px}small{display:block;color:#a50}section{break-before:page}details{margin:6px}h3{color:#14586b}.bq-badge{border-left:5px solid var(--bq-color);padding:4px;white-space:nowrap}</style>'+reportHTML(currentReport).replaceAll('<details>','<details open>'),'Obracun-'+currentReport.month+'.html','text/html');if(b.hasAttribute('data-bq-template-example'))saveFile(JSON.stringify({id:'PM-R0',type:'PM',revision:'R0',source:'Vaš troškovnik',items:[{id:'PM-R0-001',boq:'1.1',section:'A - POD',name:'Naziv rada',description:'Opis',notes:'Napomene',unit:'m2',quantity:0,unitPrice:null,order:1}]},null,2),'Novi-troskovnik-obrazac.json','application/json')}catch(err){fail(err)}});
 function fail(err){const x=document.getElementById('bq-error')||document.getElementById('ms-toast');if(x)x.textContent=err.message}
 function commit(a){const ok=root.TaskerModuleBridge.commit(a);if(!ok)throw Error('Izmena nije sačuvana. Proverite poruku u Statusu modula.');return ok}
 document.addEventListener('submit',e=>{if(!e.target.id.startsWith('bq-'))return;e.preventDefault();const f=e.target,v=Object.fromEntries(new FormData(f));try{if(f.id==='bq-progress-form'){commit({type:'boq-progress',id:ctx.m.id,phaseId:f.dataset.phase,value:v.status,percent:v.percent,effectiveOn:v.effectiveOn,startedOn:v.startedOn,note:v.note,reason:v.reason});document.getElementById('bq-dialog').close()}if(f.id==='bq-map-form'){commit({type:'boq-map',id:ctx.m.id,itemId:f.dataset.item,phaseId:v.phase});detail(f.dataset.item)}if(f.id==='bq-report-form'){commit({type:'boq-report',month:v.month,scope:v.scope});showReport(root.TaskerModuleBridge.state().boq.reports.at(-1))}}catch(err){fail(err)}});
 document.addEventListener('change',async e=>{const t=e.target;try{if(t.dataset.bqStatus)commit({type:'phase',id:ctx.m.id,phaseId:t.dataset.bqStatus,value:t.value});if(t.dataset.bqPrice)commit({type:'boq-price',templateId:t.dataset.template,itemId:t.dataset.bqPrice,price:t.value});if(t.hasAttribute('data-bq-template')){const file=t.files[0];if(!file)return;if(file.size>1000000)throw Error('JSON je prevelik.');commit({type:'boq-template',template:JSON.parse(await file.text())});admin()}if(t.dataset.bqUpload){const file=t.files[0];if(!file)return;const moduleId=ctx.m.id,phaseId=t.dataset.bqUpload;const bitmap=await createImageBitmap(file),scale=Math.min(1,1200/Math.max(bitmap.width,bitmap.height)),canvas=document.createElement('canvas');canvas.width=Math.round(bitmap.width*scale);canvas.height=Math.round(bitmap.height*scale);canvas.getContext('2d').drawImage(bitmap,0,0,canvas.width,canvas.height);bitmap.close();commit({type:'boq-evidence',id:moduleId,phaseId,image:canvas.toDataURL('image/jpeg',.7),caption:file.name});detail(ctx.m.phases.find(p=>p.id===phaseId).boqItemId)}}catch(err){fail(err)}});
 document.addEventListener('click',e=>{const b=e.target.closest('[data-bq-backup],[data-bq-backup-old]');if(!b)return;try{const old=b.hasAttribute('data-bq-backup-old'),data=old?localStorage.getItem('tasker.module-status.v1.before-boq-v1'):JSON.stringify(root.TaskerModuleBridge.state());if(!data)throw Error('Nema stare kopije: evidencija je napravljena nakon BOQ nadogradnje.');saveFile(data,old?'Status-modula-pre-BOQ.json':'Status-modula-rezervna-kopija.json','application/json')}catch(err){fail(err)}});
 root.TaskerBoqUI={mount};
})(window);

